trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  componentsProject: 'Foundation.Components/Foundation.Components.csproj'
  outputDir: '$(Build.ArtifactStagingDirectory)/nuget'
  nugetSource: 'https://pkgs.dev.azure.com/foc-poc/EGCS/_packaging/EGCS-Nuget-Feed/nuget/v3/index.json'


steps:
- task: UseDotNet@2
  displayName: 'Install .net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
     

- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Foundation.Components'
  inputs:
    command: 'build'
    projects: '$(componentsProject)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Pack Foundation.Components'
  inputs:
    command: 'pack'
    packagesToPack: '$(componentsProject)'
    configuration: '$(buildConfiguration)'
    outputDir: '$(outputDir)'
    nobuild: true


- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'
  
- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package to Azure Artifacts'
  inputs:
    command: 'push'
    publishVstsFeed: 'foc-poc/EGCS/EGCS-Nuget-Feed'
    searchPatternPush: '$(outputDir)/*.nupkg'
    arguments: '--skip-duplicate'