trigger:
  branches:
    include:
      - master
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  componentsProject: 'Foundation.Common/Foundation.Common.csproj'
  outputDir: '$(Build.ArtifactStagingDirectory)/nuget'
  nugetSource: 'EGCS-Nuget-Feed'

  isMain: $[eq(variables['Build.SourceBranchName'], 'master')]
  versionSuffix: $[iif(eq(variables['isMain'], 'True'), '', '-beta')]

name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)$(versionSuffix)

steps:
- task: UseDotNet@2
  displayName: 'Install .net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
     
- task: NuGetToolInstaller@1
  displayName: 'NuGet Tool Installer'


- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'
    

- task: DotNetCoreCLI@2
  displayName: 'Build Foundation.Common'
  inputs:
    command: 'build'
    projects: '$(componentsProject)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Pack Foundation.Components'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    command: 'pack'
    packagesToPack: '$(componentsProject)'
    configuration: '$(buildConfiguration)'
    outputDir: '$(outputDir)'
    nobuild: true
    versioningScheme: byBuildNumber


- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  
- task: NuGetCommand@2
  displayName: 'Push NuGet Package to Azure Artifacts'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    publishVstsFeed: 'EGCS/EGCS-Nuget-Feed'
    searchPatternPush: '$(outputDir)/*.nupkg'
    allowPackageConflicts: true