//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Components.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Components.Resources.ErrorsPage", typeof(ErrorsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;
        ///  An unexpected error has occurred. Please try the following:
        ///  &lt;ul&gt;
        ///      &lt;li&gt;Try refreshing the page or return later.&lt;/li&gt;
        ///      &lt;li&gt;Ensure your internet connection is working.&lt;/li&gt;
        ///      &lt;li&gt;If the problem continues, please &lt;gcds-link href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;contact us&lt;/gcds-link&gt;.&lt;/li&gt;
        ///  &lt;/ul&gt;
        ///  Return to the &lt;gcds-link href=&quot;/&quot;&gt;Home Page&lt;/gcds-link&gt;.
        ///&lt;/gcds-text&gt;.
        /// </summary>
        public static string GlobalError_Text {
            get {
                return ResourceManager.GetString("GlobalError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string GlobalError_Title {
            get {
                return ResourceManager.GetString("GlobalError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;The page you are looking for may have been moved, renamed, or is no longer available.
        ///  &lt;ul&gt;
        ///      &lt;li&gt;Check the URL for any errors.&lt;/li&gt;
        ///  
        ///      &lt;li&gt;Use the search function or browse the site’s main sections.&lt;/li&gt;
        ///  
        ///      &lt;li&gt;If you believe this is an error, please &lt;gcds-link href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;contact us&lt;/gcds-link&gt;.&lt;/li&gt;
        ///  &lt;/ul&gt;
        ///  Return to the &lt;gcds-link href=&quot;/&quot;&gt;Home Page&lt;/gcds-link&gt;.
        ///  &lt;/gcds-text&gt;.
        /// </summary>
        public static string NotFound_Text {
            get {
                return ResourceManager.GetString("NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
    }
}
