//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Web.Resources.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter your age (must be 18 or older)..
        /// </summary>
        public static string Age_Hint {
            get {
                return ResourceManager.GetString("Age_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age_Label {
            get {
                return ResourceManager.GetString("Age_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to continue..
        /// </summary>
        public static string AgreeToTerms_Hint {
            get {
                return ResourceManager.GetString("AgreeToTerms_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to Terms and Conditions.
        /// </summary>
        public static string AgreeToTerms_Label {
            get {
                return ResourceManager.GetString("AgreeToTerms_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a short biography about yourself..
        /// </summary>
        public static string Bio_Hint {
            get {
                return ResourceManager.GetString("Bio_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio_Label {
            get {
                return ResourceManager.GetString("Bio_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country of residence..
        /// </summary>
        public static string Country_Hint {
            get {
                return ResourceManager.GetString("Country_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country_Label {
            get {
                return ResourceManager.GetString("Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your date of birth.
        /// </summary>
        public static string DateOfBirth_Hint {
            get {
                return ResourceManager.GetString("DateOfBirth_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth_Label {
            get {
                return ResourceManager.GetString("DateOfBirth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Hint {
            get {
                return ResourceManager.GetString("Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter a valid email (e.g., name@example.com)..
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string Field_Firstname_Hint {
            get {
                return ResourceManager.GetString("Field_Firstname_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Field_Firstname_Label {
            get {
                return ResourceManager.GetString("Field_Firstname_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Field_Lastname {
            get {
                return ResourceManager.GetString("Field_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full name as shown on ID..
        /// </summary>
        public static string FullName_Hint {
            get {
                return ResourceManager.GetString("FullName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName_Label {
            get {
                return ResourceManager.GetString("FullName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your gender identity.
        ///.
        /// </summary>
        public static string Gender_Hint {
            get {
                return ResourceManager.GetString("Gender_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender_Label {
            get {
                return ResourceManager.GetString("Gender_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your interests?.
        /// </summary>
        public static string Interests_Label {
            get {
                return ResourceManager.GetString("Interests_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a strong password with at least 8 characters..
        /// </summary>
        public static string Password_Hint {
            get {
                return ResourceManager.GetString("Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your personal or company website URL..
        /// </summary>
        public static string Website_Hint {
            get {
                return ResourceManager.GetString("Website_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website_Label {
            get {
                return ResourceManager.GetString("Website_Label", resourceCulture);
            }
        }
    }
}
