//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global error.
        /// </summary>
        public static string ErrorTemplates_GlobalError {
            get {
                return ResourceManager.GetString("ErrorTemplates_GlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ErrorTemplates_NotFound {
            get {
                return ResourceManager.GetString("ErrorTemplates_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about the core templates included in the Foundation framework..
        /// </summary>
        public static string Index_PageDescription {
            get {
                return ResourceManager.GetString("Index_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Foundation includes two error templates:.
        /// </summary>
        public static string Section_ErrorTemplates_Description {
            get {
                return ResourceManager.GetString("Section_ErrorTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error templates.
        /// </summary>
        public static string Section_ErrorTemplates_Title {
            get {
                return ResourceManager.GetString("Section_ErrorTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bilingual splash page similar to the one used on Canada.ca..
        /// </summary>
        public static string Section_LanguageChooser_Description {
            get {
                return ResourceManager.GetString("Section_LanguageChooser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language chooser template.
        /// </summary>
        public static string Section_LanguageChooser_Title {
            get {
                return ResourceManager.GetString("Section_LanguageChooser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main layout template provides the base structure used across pages..
        /// </summary>
        public static string Section_MainTemplate_Description {
            get {
                return ResourceManager.GetString("Section_MainTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main template.
        /// </summary>
        public static string Section_MainTemplate_Title {
            get {
                return ResourceManager.GetString("Section_MainTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error templates.
        /// </summary>
        public static string SideNav_ErrorTemplates {
            get {
                return ResourceManager.GetString("SideNav_ErrorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page.
        /// </summary>
        public static string SideNav_Label {
            get {
                return ResourceManager.GetString("SideNav_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language chooser template.
        /// </summary>
        public static string SideNav_LanguageChooser {
            get {
                return ResourceManager.GetString("SideNav_LanguageChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main template.
        /// </summary>
        public static string SideNav_MainTemplate {
            get {
                return ResourceManager.GetString("SideNav_MainTemplate", resourceCulture);
            }
        }
    }
}
